title = "Surya Nallaparaju"
baseURL = ""
theme = "PaperMod"

enableRobotsTXT = true
enableEmoji = true

[params]
description = "PaperModX Example Site description"
author = "Reorx"
images = ["cover.png"]
favicon = "favicon.ico"
DateFormat = "2006-01-02"
useCustomAnalytics = true
mainSections = ["posts", "notes"]

# theme params
DisableLanguageSwitch = true
TocOpen = true
TocSide = "right"
EnableInstantClick = false
EnableImageZoom = true
ShowShareButtons = true
ShareButtons = ["twitter", "telegram"]
ShowReadingTime = true
ShowWordCount = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
Email = "hello@example.com"

[params.socialAccounts.twitter]
username = ""

[params.homeInfoParams]
Title = "Student / Tinkerer"
Content = """

"""

[permalinks]
posts = "/:year/:month/:slug/"

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

[menu]
[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 1
[[menu.main]]
name = "Notes"
url = "/notes/"
weight = 2
[[menu.main]]
name = "Research"
url = "/research/"
weight = 3
[[menu.main]]
name = "Archives"
url = "/archives/"
weight = 4

[languages.en]
languageName = "English"

[markup]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "dracula"
lineNos = false
noClasses = false